namespace XperiCad.DigitalDrawingStore.BL.Impl.Services
{
    public enum CultureProperty
    {
        APPLICATION_NAME,
        HOME_PAGE_NAME,
        PRIVACY_PAGE_NAME,
        ERROR_PAGE_NAME,
        DOCUMENTS_PAGE_NAME,
        CATEGORIES_PAGE_NAME,
        SETTINGS_PAGE_NAME,
        EVENTS_PAGE_NAME,

        DOCUMENT_NAME_CATEGORY_NAME,

        SEARCH_BUTTON_TEXT,
        SHOW_EMPTY_CATEGORIES_CHECKBOX_TEXT,
        COPYRIGHT,
        SEARCHABLE_FIELDS_TEXT_1,
        SEARCHABLE_FIELDS_TEXT_2,
        SEARCHABLE_FIELDS_TEXT_3,
        SEARCHABLE_FIELDS_TEXT_4,
        EMPTY_CATEGORY_TEXT,

        OPEN_EDITOR_TEXT,
        CLOSE_EDITOR_TEXT,
        OUTER_WATERMARK_POSITION_TEXT,
        DOCUMENT_USAGE_TEXT,
        MIDDLE_WATERMARK_HORIZONTAL_OFFSET_TEXT,
        MIDDLE_WATERMARK_VARTICAL_OFFSET_TEXT,
        FONT_SIZE_TEXT,
        WATERMARK_TRANSPARENCY_TEXT,
        UPDATE_TEXT,
        TOP_LEFT_WATERMARK_TEXT,
        TOP_RIGHT_WATERMARK_TEXT,
        BOTTOM_LEFT_WATERMARK_TEXT,
        BOTTOM_RIGHT_WATERMARK_TEXT
    }
}
